# rename filename to magi-config.yaml

# base configs
app:
  # Optional, default: Magi
  name: MagiMax
  # Optional, release or debug, default: release
  runMode: release
  # Optional, default: 0.0.0.0
  host: 0.0.0.0
  # Optional, default: 8086
  port: 8086
  # Optional, debug, info, warn, error, panic, default: info
  logLevel: info
  # Optional, info, warn, error, silent, default: warn
  dbLogLevel: warn
  # Optional, default: false
  uiLog: false
  # Optional, ==it is best to modify it==，default: Magi
  jwtSecret: Magi
  # Optional, uint second, default: 86400
  jwtTimeout: 86400

# db configs
db:
  mysql:
    # Required
    host: 127.0.0.1
    # Optional, default: 3306
    port: 3306
    # Required
    user: root
    # Required
    password: root
    # Optional, default: magi
    name: magi
    # Optional, default: true
    migrate: true
    # Optional, uint millisecond, default: 2000
    slowThreshold: 2000

# git configs
git:
  # Required
  type: github
  # Required
  hostname: github.com
  # Required
  repo: "https://github.com/xxx/magi"
  # Required
  username: magi
  # Required
  token: "xxx"
  # Required
  personal: true
  # Required
  private: true
  # Optional, default: main
  branch: main